[package]
name = "argent_contracts"
version = "0.1.0"
license-file = "LICENSE"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.19.0" }
# openzeppelin_token = "0.19.0"
starknet = "2.8.5"

[dev-dependencies]
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.34.0" }
# assert_macros = "2.8.5"
snforge_std = "0.34.0"
cairo_test = "2.8.5"

[[target.starknet-contract]]
sierra = true
casm=false

[scripts]
test = "snforge test"

[cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
